
services:
  k6:
    image: grafana/k6
    volumes:
      - ./k6:/scripts
      - ./results:/results

  influxdb:
    image: influxdb:1.8
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml
    depends_on:
      - influxdb